name: Run e2e tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://docker:docker@postgres:5432/apisolid?schema=public
      JWT_SECRET: testing-secret

    services:
      postgres:
        image: bitnami/postgresql
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid
          
        options: >-
          --health-cmd="pg_isready -U docker -d apisolid"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Apply migrations
        run: npx prisma migrate deploy

      - name: Run e2e tests
        run: npm run test:e2e
